name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event.sender.avatar_url) }}
        run: echo "$GITHUB_CONTEXT"
      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event.head_commit.author.username) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Now it is
        run: |
          echo ${{ github.repositoryUrl }}
      - name: Deployment success
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          avatarUrl: ${{ github.event.sender.avatar_url }}
          description: to https://calm-wildwood-40210.herokuapp.com/ by ${{ github.event.head_commit.author.username }}
          details: ""
          text: A new version of Pokedex deployed
